package org.core;

/**
 * immutable
 * hashcode, equals generated by default
 * we can inject methods
 * no non-static things
 * no extend class, cannot be extended
 * implements interfaces
 * compact constructor is possible, if you need some validations etc...
 */
public record Person(int id, String firstName, String lastname, String email, String gender, Integer age) {

    //compact constructor
    public Person {
        if (id < 0) throw new IllegalArgumentException("not valid person id!");
    }
}
